### ISSUE TITLE
Heroku GitHub Integration Broken

### ISSUE THREAD

**Issue by Rogibb111** [Rogibb111/Ski-Resort-Dashboard#55]
The heroku integration no longer seems to be working for me any more. I was consistnently getting errors when trying to deploy. After trying to re-connect it through heroku by disconnecting the integration and reconnecting it again, I can no longer even get it to connect to my GitHub account. I think instead I will trying using the Heroku Deploy GitHub Action and add it to my release workflow. This way I can control when I deploy to Heroku and set it to only happen on a release.

### TODO

- [x] Add Heroku-Deploy GitHub Action to workflow
- [x] Add Id to Semantic-Release step and reference in conditionals for other workflow steps
- [x] Fix tags after setting up deploy
- [x] Add Heroku API key to secrets
